--- #YAML:1.0
name:                weblint++
version:             1.15
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    ConfigReader::Simple:          1.15
    Data::Dumper:                  0
    Digest::MD5:                   0
    HTML::Lint:                    0
    HTML::SimpleLinkExtor:         0
    HTTP::Request:                 0
    HTTP::SimpleLinkChecker:       0
    HTTP::Size:                    0.4
    Mail::Sendmail:                0
    Test::File:                    0
    Test::More:                    0
    Text::Diff:                    0
    Text::Template:                0
    Time::HiRes:                   0
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - brian d foy <bdfoy@cpan.org>
